### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by hannseman** [klarna/kco-mobile-sdk#10]
It would be really nice if the iOS-library would get support for Carthage.

https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file

**Comment by danieloskarsson** [comment]
I agree. Having to introduce CocoaPods next to Carthage in the project just to use Klarna is not nice.

**Comment by gbanfalvikl** [comment]
Hi, we're reworking our CI and release process (both internal and external). As part of that, we'll be making more frequent releases and supporting Carthage as well as CocoaPods. 

As a result of this, the iOS project has undergone significant changes, so we want to test that everything works properly before our next large release.

Carthage support is working internally. We'll keep you updated and let you know as soon as it's out.

**Comment by hannseman** [comment]
@gbanfalvikl any update on this?

**Comment by NanDotWang** [comment]
Hi, we are closing the issue, as we have add and verified Carthage support, please check README for details.

**Comment by aborren** [comment]
@NanDotWang @gbanfalvikl  I am sadly not able to verify this support. Please have a look at https://github.com/klarna/kco-mobile-sdk/issues/30
