### ISSUE TITLE
Black screen when opening the checkout view controller in iOS 11

### ISSUE THREAD

**Issue by eFagerman** [klarna/kco-mobile-sdk#14]
With iOS 10 it works fine. However, when a running the project on a iOS 11 (Swift 4.0) device the checkout view is complete black.

**Comment by mitemitreski** [comment]
Can you please send it bit more info. I do know we have some users that are running us from swift already in production. 

Either way we will have a look

**Comment by NanDotWang** [comment]
@eFagerman , are you still experiencing this issue ? 

If so, please provide more info (best with a demo project to reproduce this issue). Thank you :)

**Comment by eFagerman** [comment]
No, you can close this issue.

//erik

Den tis 8 jan. 2019 kl 14:42 skrev Nan <notifications@github.com>:
