### ISSUE TITLE
Cocoapod of KlarnaCheckoutSDK does not have a KlarnaCheckout module available for import in swift project

### ISSUE THREAD

**Issue by ghost** [klarna/kco-mobile-sdk#16]
Recently updated from `pod KlarnaCheckout` (1.5.0) to `pod KlarnaCheckoutSDK` (1.6.1). This causes an issue where the `KlarnaCheckout` module does not exist and can not be imported.

Podfile:
```
platform :iOS, '9.0'
target 'Project' do
  use_frameworks!
  inhibit_all_warnings!

  ...
  pod 'KlarnaCheckoutSDK'
  ...
end
```

Calling `pod install` successfully updates the old `KlarnaCheckout` pod to the new `KlarnaCheckoutSDK` pod but the problem is inside Xcode.

`import KlarnaCheckout` shows `No such module 'KlarnaCheckout'` weirdly when typing import, KlarnaCheckout autocompletes as a module..

Project is using Swift 3, supporting iOS 9+

`pod --version`
1.3.1

macOS version
High Sierra 10.13.1 (I also ran into this problem in Sierra)

xcode version
Version 9.1 (9B55) (I also ran into this problem in 8)

**Comment by ghost** [comment]
Check out the test [project](https://github.com/jinhongfyndiq/testing-klarna-checkout-upgrade)

The master branch has `pod KlarnaCheckout` and the update-sdk branch has `pod KlarnaCheckoutSDK`. The update-sdk branch fails as described above.

**Comment by ghost** [comment]
Also check out this test [project](https://github.com/jinhongfyndiq/testing-klarna-checkout-new)

This project was using `pod KlarnaCheckoutSDK` from the beginning and it fails as described still.

**Comment by gbanfalvikl** [comment]
Hi! Apologies for the late reply, we're looking at it and will get back you ASAP.

**Comment by gbanfalvikl** [comment]
Can you try importing KlarnaCheckoutSDK instead? The module was renamed.

**Comment by ghost** [comment]
throws `No such module 'KlarnaCheckoutSDK'` @gbanfalvikl

**Comment by ghost** [comment]
Updated the issue description with more details @gbanfalvikl

**Comment by gbanfalvikl** [comment]
Hi, we tested the project you linked to. Thanks for sending us a sample! The issue is caused by a mislabeled modulemap. A temporary solution for this is:

1. Adding a bridging header to the project to import the main KCO header into Swift:

```objective-c
#import <KlarnaCheckoutSDK/KlarnaCheckout.h>
```

2. Renaming the module in the `module.modulemap`to `KlarnaCheckoutSDK`. It should be located in `Pods/KlarnaCheckoutSDK/ios/KlarnaCheckoutSDK.framework/Modules/module.modulemap`. It should look something like:

```
framework module KlarnaCheckoutSDK {
    umbrella header "KlarnaCheckout.h"
    export *
    module * { export * }
}
```

We understand that it's not ideal. We'll be releasing a new version in the coming weeks that addresses this issue.

Please let us know if it worked for you!

**Comment by andreasmpet** [comment]
Any resolution to this issue?

Trying 1.6.1 at the moment, and I still can't import the module, nor is there a modulemap file for KlarnaCheckoutSDK

What's the ETA for a new release?

EDIT: The modulemap was there, just not referenced in the xcodeproj file like in all the other pods. Workaround works for now, but I'm kind of worried that this hasn't been fixed in 3 months!

**Comment by morten-hogseth** [comment]
Unable to import module in 1.6.1, please prioritize this!

**Comment by gbanfalvikl** [comment]
Hi, we're testing a new release internally now. We'll have a a new version 1.6.2 out later this week or early next week. We apologise for the inconvenience.

**Comment by andreasmpet** [comment]
Thanks! While you're here (apologies for slightly straying slightly off topic), could you clarify a point in this documentation for me: https://developers.klarna.com/en/gb/kco-v3/checkout/mobile-apps/ios-native-approach 

```
- (void)handleNotification:(NSNotification *)notification
{
    NSString *name = notification.userInfo[KCOSignalNameKey];
    NSDictionary *data = notification.userInfo[KCOSignalDataKey];

    if ([name isEqualToString:@"complete"]) {
        if (uri && [uri isKindOfClass:[NSString class]] && uri.length > 0) {
            NSURL *url = [NSURL URLWithString:uri];
            checkout.snippet = confirmationSnippet;
        }
    }
}
```

I don't understand where the local variables confirmationSnippet or uri is coming from. Also, what are the different names that the signal can have? Is there one for errors, and handling them?

**Comment by gbanfalvikl** [comment]
That looks like somebody needs to review the documentation. Developers only need to render the URL from the the complete signal. 

We're also hosting documentation [on GitHub](https://github.com/klarna/kco-mobile-sdk/blob/master/ios/README.md) and I'll get in touch with the owner of the developers site to update this text.

Apologies for that.

**Comment by andreasmpet** [comment]
I read your docs on github too, but they don't mention any handling of the return signal in the "native" section, only the "hybrid" one. The lack of this led me to believe that the other documentation was the most up to date.

**Comment by mitemitreski** [comment]
We gonna update this as soon as possible to reflect reality. Thanks for bringing it up.

**Comment by hakan4** [comment]
is there an update on this issue yet?

**Comment by gbanfalvikl** [comment]
Hi! We apologise for the delay. 

We're working on more substantial changes and we were aiming to incorporate this fix to the next release, but given how long it's taking, we'll be making a release with **just this fix**, tomorrow.

**Comment by gbanfalvikl** [comment]
New release is out!

**Comment by juleadam** [comment]
Works, ty

**Comment by ghost** [comment]
Works. Thanks. Closing the issue.
