### ISSUE TITLE
Android Can't take screen shot due to security policy

### ISSUE THREAD

**Issue by belalfyndiq** [klarna/kco-mobile-sdk#17]
Loading KlarnaCheckout in a Fragment and Stacking this Fragment it make it prevents the Activity from  taking a screenshot thats all ok but when the Fragment is removed from the back stack (the checkoutFragment is Destroyed), it's still preventing the activity from taking a screenshot.

**Comment by gbanfalvikl** [comment]
Thanks for the heads up! We got a bunch of fixes and improvements in the next Android Release, and we'll see if we can fit this one in.

**Comment by omarbh** [comment]
Hi @belalfyndiq This has been fixed in the version 1.6.5.
