### ISSUE TITLE
Elements in the webview is cut off on initial load

### ISSUE THREAD

**Issue by ghost** [klarna/kco-mobile-sdk#18]
**Problem**
When the checkout is loaded without any saved data and thus prompting for user email & postcode, the top of the content is cut off (see screenshots).

It corrects itself after switching the field from email to postcode using the arrow keys on the keyboard (see screenshots).

Happens on all simulators and physical devices.

**How it is set up in code**
`CheckoutViewController` snippets:
```
import KlarnaCheckoutSDK

class CheckoutViewController: UIViewController {
    private var checkout: KCOKlarnaCheckout!
    override function viewDidLoad() {
        super.viewDidLoad()
        setupCheckoutView()
        setSnippet()
    }
    private func setupCheckoutView() {
        let checkout = createKCOKlarnaCheckout()
        let viewController = checkout.checkoutViewController as UIViewController & KCOCheckoutViewControllerProtocol
        contentView.addSubview(viewController.view)
        addChildViewController(viewController)
        viewController.view.addConstraintsToFillParentView(contentView)
        viewController.didMove(toParentViewController: self)
        self.checkout = checkout
    }
    private func createKCOKlarnaCheckout() -> KCOKlarnaCheckout {
        guard let url = URL(string: "my-schema")!
        guard let checkout = KCOKlarnaCheckout(viewController: self, return: url)
        return checkout
    }
    private func setSnippet() {
        checkout.setSnippet("the klarna checkout snippet returned from our server")
    }
}
```

**Screenshots**
![initial](https://user-images.githubusercontent.com/25151405/39048222-f47399ce-449c-11e8-885d-1a650c452284.png)
![after changing field](https://user-images.githubusercontent.com/25151405/39048231-f8d6903e-449c-11e8-9914-c1565e388b31.png)

**Comment by d4rkd3v1l** [comment]
Same here :-(

**Comment by gbanfalvikl** [comment]
Hi, we're aware of the issue and we're doing our best to identify/fix it. One of underlying HTML components is misplaced under very specific circumstances with UI and WKWebView.

**Comment by mitemitreski** [comment]
@gbanfalvikl this was fix in the underlying web app right ?

**Comment by ghost** [comment]
If it helps, @mitemitreski @gbanfalvikl I "resolved" this issue by using the webView method (despite the documentation telling me not to...) for now. 

I would like to implement the hybrid approach again when this is fixed.

**Comment by rakshitsoni02** [comment]
any workaround on this issue? as I'm also facing the same.

**Comment by ghost** [comment]
> any workaround on this issue? as I'm also facing the same.

@rakshitsoni02 I managed to do a workaround by using the deprecated webView method (I think its called the "hybrid" method according to their docs; I had the issue when implementing the "native" method) but as you may have noticed, they're not very responsive here, maybe try their customer support page on their website?

**Comment by rakshitsoni02** [comment]
@jkhwork thank you for suggesting.

**Comment by omarbh** [comment]
@jkhwork  @rakshitsoni02 @d4rkd3v1l  We have identified the bug and we are working on a fix on Javascript side. The fix is estimated to be release next week! no changes are required from your side. Big thanks for reporting this 👍

**Comment by omarbh** [comment]
@jkhwork @rakshitsoni02 @d4rkd3v1l We have done a release on Javascript  that contains a fix for this. if you do not experience anymore this then I will close this issue

**Comment by omarbh** [comment]
I will closed this issue as it's fixed

**Comment by rakshitsoni02** [comment]
@omarbh is there anything I need to change? as I can see elements are still not appearing completely on stage environment android SDK `1.6.8`

**Comment by omarbh** [comment]
Hi @rakshitsoni02! You do not need to change anything, this should not be possible to reproduce anymore. Recently we have changed the layout of the initial elements with an enhanced one. could you take a screenshot and we we will look into this again!

**Comment by rakshitsoni02** [comment]
![img_1990](https://user-images.githubusercontent.com/8371249/52625631-b6a70900-2eb1-11e9-9a41-9fa40cea13b6.JPG)

Please have a look in the above picture. bottom icons are not completely visible.
it's same in iOS as well

**Comment by omarbh** [comment]
Thanks @rakshitsoni02 for reporting 👍 ! however this is a separate issue, could please create a separate issue and include the order_id along side the screenshot and the frequency of this bug

**Comment by rakshitsoni02** [comment]
@omarbh reported [here](https://github.com/klarna/kco-mobile-sdk/issues/27)
