### ISSUE TITLE
No notification received when adding listener on KCOSignal

### ISSUE THREAD

**Issue by DanielLeberle** [klarna/kco-mobile-sdk#19]
Hi everyone,

I implemented the SDK and was able to make a purchase with demo data.
I also added an observer to the notification `Notification.Name.KCOSignal` but I never get any notification from the SDK about the current status of the purchase.

Is there anything else I need to implement?

I use Klarna SDK 1.5.0 and everything is implemented in Swift with the XCode Version 9.3.1

**Comment by gbanfalvikl** [comment]
Hi, there's an SDK release version 1.6.2. Could you try with that?

**Comment by DanielLeberle** [comment]
I updated to 1.6.2 but still no notifications

**Comment by gbanfalvikl** [comment]
Alright, we're looking into it. We'll get back to you ASAP!

**Comment by DanielLeberle** [comment]
Are there any updates on this issue?

**Comment by gbanfalvikl** [comment]
We've looked into it and it seems to work for us fine. What notifications are you missing? Are you getting the complete signal when the checkout completes?

**Comment by DanielLeberle** [comment]
Unfortunately I don't receive any notifications from the SDK. I downloaded your demo project and everything works fine but it is Obj-C and I am using Swift. Do you think that might be an issue? Do you have a Swift Example where everything works?

**Comment by DanielLeberle** [comment]
I just added a Swift observer to your Demo project and everything works fine. So I guess the error is in our app implementation. The weird thing is I just registered for all notifications and I also get a "KCOJavaScriptContextCreateNotification" notification but never a "KCOSignalNotification".
Currently I work in a dev environment, is that maybe the problem?
And I only set the snippet on the KCOKlarnaCheckout object and then I show the objects checkoutViewcontroller. Am I missing something?

**Comment by DanielLeberle** [comment]
Another Update: I just copied your code and opened a UIVIewController containing a UIWebView with the same url that you use in your demo project. I also call notifyViewDidLoad and I can make a purchase just as in the demo app. 
But also with this implementation I don't receive "KCOSignalNotification", I receive only "KCOJavaScriptContextCreateNotification".

**Comment by MKGitHub** [comment]
Hi @DanielLeberle

Would you please be kind and send an email to mobile.sdk (a) klarna.com and we will investigate.

In the email please add this reference to this issue i.e.
"Reference: https://github.com/klarna/kco-mobile-sdk/issues/19"

Please attach a Xcode project demonstrating the issues that you are experiencing and also please add comments and notes to the code.

Add comments for what behaviour you would expect and what your are experiencing instead.

The sample code should clearly demonstrate the your apps implementation, observers, notifications and snippets.

Thank you, and we are looking forward to your email!

**Comment by omarbh** [comment]
Hi @DanielLeberle, if you the issue is fixed then we will mark this issue as resolved 👍
