### ISSUE TITLE
KCOSignalDataKey: dictionary incomplete

### ISSUE THREAD

**Issue by airspeed** [klarna/kco-mobile-sdk#20]
Hallo Klarna Team,

Is it by design that the `KCOSignalDataKey` dictionary only contains changes to country and zip code?
It would be very nice if we could extract all entered customer data at form send time.
Or is this a security concern?

Thanks a lot and keep up the good work :)

EDIT: Unless I am doing something very wrong it should not matter, but anyway for context`s sake here it is about the iOS SDK v1.6.2.
:)

**Comment by omarbh** [comment]
Hi @jkhwork , For the signals **billing_address_change**  and **shipping_address_change** the data that's shared depends on the **billing country**.  For example in UK we are sharing more data than just zip code and country, you can check here https://developers.klarna.com/en/gb/kco-v3/checkout/javascript-api/  however for other country such as Sweden we are sharing just country and zip code, example se

**Comment by airspeed** [comment]
Hi @omarbh,
thanks so much, that clarifies it. :)
