### ISSUE TITLE
Can't implement the SDK to android studio

### ISSUE THREAD

**Issue by www0488** [klarna/kco-mobile-sdk#21]
By following the step by step guide, I tried to implement the sdk to my project. But I can't even make that work.

**When I'm trying manually install the sdk:**
My file name is : klarna with extension are
project build:

repositories {
        google()
        jcenter()
        mavenCentral()
        flatDir {
            dirs 'libs'
        }
    }

app build:
    implementation (name: 'klarna', ext: 'aar')

I got error: 

ERROR: Failed to resolve: :klarna:
Affected Modules: app

**When I'm trying to implement the Klarna SDK with maven:**

project build: 

 repositories {
        google()
        jcenter()
        mavenCentral()
    }

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
}

app build:

    implementation 'com.klarna.checkout.sdk:klarna-checkout-sdk:1.5.0'

error message:

ERROR: Failed to resolve: com.klarna.checkout.sdk:klarna-checkout-sdk:1.5.0
Show in Project Structure dialog
Affected Modules: app

**Comment by www0488** [comment]
Fixed, mixed up between app build and project build

**Comment by mitemitreski** [comment]
good to hear, we are looking into simplifying this step as well.
