### ISSUE TITLE
Provide a list of all notification names in the documentation

### ISSUE THREAD

**Issue by ghost** [klarna/kco-mobile-sdk#23]
It should be clear what notification signals there are for `KCOSignalNameKey` and `KCOSignalDataKey` in the documentation. Currently only "complete" is mentioned in the [documentation](https://github.com/klarna/kco-mobile-sdk/blob/master/ios/README.md#completion-1) for the `KCOSignalNameKey`.

A complete list (including error signals) should be in the documentation.

**Comment by omarbh** [comment]
@jkhwork Thank for reporting this 👍 you can check the documentation here https://developers.klarna.com/en/gb/kco-v3/checkout/javascript-api/  for the list of KCOSignalNameKey and the correspondent KCOSignalDataKey. This signal data depends on the country. We will update the docs to point to this information.

**Comment by adrianpalmquist** [comment]
A link has been added to the docs.
