### ISSUE TITLE
Android: Crash when link is clicked in checkout view

### ISSUE THREAD

**Issue by TillSimon** [klarna/kco-mobile-sdk#24]
We are experiencing crashes when a simple web-url-link is clicked in the checkout view. It doesn't seem to have to do with the link itself, but rather some Android resource.
We did so far only see it on Galaxay S5, Android 4.4, so possibly this is an issue with older devices.

Stacktrace:
![image](https://user-images.githubusercontent.com/738058/49375964-0d4fd400-f706-11e8-88c9-27daec15979a.png)

**Comment by omarbh** [comment]
@TillSimon Thanks for reporting this 👍 .  Can you specify which version of the SDK did you use ?

**Comment by TillSimon** [comment]
Sure
`com.klarna.checkout:sdk:1.6.5`

**Comment by ajantabisht** [comment]
@TillSimon Thank you for reporting the issue. We can reproduce this issue in our staging environment and added a ticket in our backlog for the same. Will try to fix it as soon as we can.
Feel free to reach out for further questions.

**Comment by omarbh** [comment]
Hi, this will be fixed in the new in-app sdk.
