### ISSUE TITLE
Build failed with 1.6.8 it was working with JAR

### ISSUE THREAD

**Issue by rakshitsoni02** [klarna/kco-mobile-sdk#25]
More than one file was found with OS independent path 'META-INF/androidx.localbroadcastmanager_localbroadcastmanager.version'

**Comment by gbanfalvikl** [comment]
Hi! Do you have a more complete error or stack-trace?

**Comment by rakshitsoni02** [comment]
hi, I solved by migrating to androidX 
Solution is here
https://stackoverflow.com/questions/51280090/what-is-androidx
