### ISSUE TITLE
klarna  No creating session IOS and getting this error.

### ISSUE THREAD

**Issue by dev-dubaisoftwaresolutions** [klarna/kco-mobile-sdk#26]
FashionStore-CocoaPods[9347:135672] CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    ptcl = htps;
    "r_Attributes" = 1;
    sdmn = "very closed site";
    srvr = "api.playground.klarna.com";
    sync = syna;
}
BackendOperations createDataTask: The data couldn’t be read because it isn’t in the correct format.

**Comment by omarbh** [comment]
Hi, could your provide more details about the issue. is This KCO or KP?

**Comment by omarbh** [comment]
Hi @dev-dubaisoftwaresolutions  I will close this issue as we do not have enough information to investigate the issue.
