### ISSUE TITLE
footer of the web-view not visible completely

### ISSUE THREAD

**Issue by rakshitsoni02** [klarna/kco-mobile-sdk#27]
**orderId**: b29753f1-73ae-42be-bec0-52819c5e7bac
Frquency: every time
Platform: both android (Ver 1.6.8) & iOS
Reference:
![img_1990](https://user-images.githubusercontent.com/8371249/52634274-15c34880-2ec7-11e9-900f-e11f1780e2a6.JPG)

**Comment by omarbh** [comment]
Thanks @rakshitsoni02 we will look into this and we will come back with more details 👊

**Comment by omarbh** [comment]
Hi @rakshitsoni02 the should be fixed in the latest version of CheckoutSDK Android 1.6.13. I will close this ticket please feel free to open if the issue still there!
