### ISSUE TITLE
Android: Crash when recreating killed checkout activity

### ISSUE THREAD

**Issue by TillSimon** [klarna/kco-mobile-sdk#29]
We are experiencing crashes when the activity containing the checkout view was killed when in the background due to low memory and then being recreated.
To be reproduced with _Deverloper Options -> Don't keep activities_.
If you then initiate a klarna checkout and simply put the app in the background and then restart it again, the crash happens.
Version: `com.klarna.checkout:sdk:1.6.8`

Crash:
`Caused by: android.app.Fragment$InstantiationException: Unable to instantiate fragment a.b.a.a: make sure class name exists, is public, and has an empty constructor that is public`

**Comment by kitek** [comment]
@TillSimon for me it looks the same like [#28] 
Any progress with this issue @omarbh ?

**Comment by patrikfigura** [comment]
@TillSimon @kitek Hey, issue should be fixed in `1.6.10` release (if you are using support library use `1.6.10-support`). Let me know if it fixed your problem

**Comment by omarbh** [comment]
@TillSimon @kitek is this still an issue for you? otherwise I will close this issue

**Comment by kitek** [comment]
@omarbh I think it's solved. Thank you.
