### ISSUE TITLE
Cannot install via Carthage

### ISSUE THREAD

**Issue by aborren** [klarna/kco-mobile-sdk#30]
Hi, I'm trying to add the kco-mobile-sdk via Carthage. I have added `github "klarna/kco-mobile-sdk"` to the Cartfile as stated in the README.

When I run `carthage update kco-mobile-sdk` I get the following issue.

`*** Skipped building kco-mobile-sdk due to the error:
Dependency "kco-mobile-sdk" has no shared framework schemes`

Am I doing something wrong or is there is anything I can do about it. Many other projects with similar issues have forgotten to add the shared scheme to the git project.

**Comment by omarbh** [comment]
Hi @aborren ! thanks for reporting this. We will look into it and get back to you as soon as possible.

**Comment by aborren** [comment]
Any updates regarding this?

**Comment by mBrissman** [comment]
Having the same problem.

**Comment by polar133** [comment]
Hi @mBrissman, did you added this line into your Cartfile ? 

`binary "https://raw.githubusercontent.com/klarna/kco-mobile-sdk/master/KlarnaCheckoutSDK.json"`

please, can you share how are you integrating KCO in your cartfile? thanks.

**Comment by mBrissman** [comment]
Hi @polar133! 

Thank you for the fast response!

No, I just added the line mentioned in the readme of your repo: `github "klarna/kco-mobile-sdk"`

But the binary works. 👍

**Comment by polar133** [comment]
@mBrissman thanks for the update!
