### ISSUE TITLE
Unable to archive with manually added framework

### ISSUE THREAD

**Issue by aborren** [klarna/kco-mobile-sdk#31]
Hi, seeing as Carthage is not working #30 I have tried to add the framework manually. This works when running the device on simulator and device in debug mode. However when trying to archive the project I am facing the following error:

`bitcode bundle could not be generated because './KlarnaCheckoutSDK.framework/KlarnaCheckoutSDK' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file './KlarnaCheckoutSDK.framework/KlarnaCheckoutSDK' for architecture arm64`

This is for `v1.6.5` of the framework which is the latest uploaded one at this date. 

Any comments or ideas on how to solve this? I hope you are able to solve this and #30 soon.

**Comment by aborren** [comment]
Disabling Bitcode makes it possible to archive it, however that is not something I want to do...

**Comment by aborren** [comment]
And it creates the following error when uploading to AppStore Connect. 

`App Store Connect Operation Error
ERROR ITMS-90087: "Unsupported Architectures. The executable for App.app/Frameworks/KlarnaCheckoutSDK.framework contains unsupported architectures '[x86_64, i386]'."`

This can be bypassed by stripping the unsupported architectures in a Run Script Phase.

**Comment by omarbh** [comment]
This will be fixed in the new sdk, I will close this, @aborren  please feel free to open it again if you still have any question
