### ISSUE TITLE
WebView content too large and cut off

### ISSUE THREAD

**Issue by d4rkd3v1l** [klarna/kco-mobile-sdk#35]
We just noticed that the WebView content is way too large and therefore cut off, as you can see in attached screenshot.
I don't think this is an SDK issue, but unfortunately I didn't find a better place to report this.

KlarnaCheckoutSDK (1.6.2, 1.6.6)
iOS 12 & 13
iPhone XS

![Simulator Screen Shot - iPhone Xs - 2019-10-08 at 16 53 34](https://user-images.githubusercontent.com/13336238/66407253-322f6a80-e9ed-11e9-8fd3-0d4dcc5f044b.png)

**Comment by omarbh** [comment]
Hi @d4rkd3v1l thanks for reporting this, we have fixe this issue recently, could you check if you can still reproduce it ?

**Comment by d4rkd3v1l** [comment]
Thanks a lot, seems like it works now as expected :-)
