### ISSUE TITLE
Status of this repository

### ISSUE THREAD

**Issue by gildebrand** [klarna/kco-mobile-sdk#5]
I got recommended this repository from our enterprise integration manager at Klarna, since we use KCO in our Ionic (Cordova) app. I have a couple of questions that I feel that the readme doesn't answer to.

Is this solution ready to be used in production apps, or is it still under construction? If it's ready to be used, I feel that the readme could use some love (integration example).

Also what problem does this solve? I know that it's been kind of problematic to use KCO in Cordova, does this project provide a solution for those problems?

If it's not production ready, when will it be?

Tack på förhand!

**Comment by akelagercrantz** [comment]
I would also love to hear an answer to the questions posted above. @niklasdstrom @vectart

**Comment by HeyHugo** [comment]
I'm in the same boat, some documentation would be really helpful.

**Comment by mitemitreski** [comment]
We are re-starting the project. It has been production ready since day one. But I suggest anyone to wait out till the next release.
