### ISSUE TITLE
Swift Package Manager Support for Xcode 12

### ISSUE THREAD

**Issue by rresma2** [klarna/kco-mobile-sdk#51]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

The current `Package.swift` file uses an outdated Xcode tools version

```
because kco-mobile-sdk >=1.3.0 contains incompatible tools version and root depends on kco-mobile-sdk 1.6.12..<2.0.0, version solving failed.
```

I'd like to request you guys to update to swift-tools-verison 5.3.

```
// swift-tools-version:5.3
// The swift-tools-version declares the minimum version of Swift required to build this package.
```

**Describe alternatives you've considered**

Using KlarnaCheckout in Cocoapods

**Additional context**

Our team at Wish is migrating away from Cocoapods in favor of Swift Package Manager and this framework is blocking the full transition.

**Comment by polar133** [comment]
Hi @rresma2 , we update to version 1.6.13, please give a try and let us know if that one works for your project.

**Comment by rresma2** [comment]
Hi @polar133 this is what I'm seeing right now on master.

```
import PackageDescription

let package = Package(
    name: "KlarnaCheckoutSDK"
)
```

You'd need to have something like this?

```
// swift-tools-version:5.3
// The swift-tools-version declares the minimum version of Swift required to build this package.
import PackageDescription

let package = Package(
    name: "KlarnaCheckoutSDK"
)
```

**Comment by rresma2** [comment]
Package Resolution Failed

`kco-mobile-sdk.git`

```
because kco-mobile-sdk >=1.3.0 contains incompatible tools version and root depends on kco-mobile-sdk 1.6.13..<2.0.0, version solving failed.
```

**Comment by polar133** [comment]
Thanks for the update @rresma2. I will give a look at it and be back later when we have some updates to share.

**Comment by polar133** [comment]
Hi @rresma2. For making it available in SPM we would need more time as we need to migrate to xcframework. So i can't give an estimated time when it will be released. We will try to make it available ASAP but we need to test it more before.

**Comment by polar133** [comment]
Hi @rresma2. We release 1.6.14 which contains support for swift package manager. Please, give a try and let us how did it go.
