### ISSUE TITLE
iOS Crash after BankID sign in 

### ISSUE THREAD

**Issue by ghost** [klarna/kco-mobile-sdk#55]
**Describe the bug**
App is crashing when user singing transaction using BankID using Klarna Checkout. Crashes started to occur around 4th Ocotober 

> Fatal Exception: NSInternalInconsistencyException
> View has lost track of its superview, most likely through unsupported use of CALayer API on the view's layer. If this isn't a crash yet, it will be in the near future. Problem view: <UIWebOverflowScrollView: 0x1067c6600; frame = (0 0; 320 548); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x28058a7f0>; layer = <WebLayer: 0x2808156a0>; contentOffset: {0, 86}; contentSize: {320, 1197}; adjustedContentInset: {0, 0, 0, 0}> Expected parent: <UIWebBrowserView: 0x12c1c4c00; frame = (0 0; 320 568); text = ' Betalningssätt H Hulja ...'; opaque = NO; gestureRecognizers = <NSArray: 0x28058b4b0>; layer = <UIWebLayer: 0x2808a50e0>> Break on UIViewReportBrokenSuperviewChain to debug.

**To Reproduce**
1. Go to Klarna Checkout 
2. Select payment with BankID 
3. Login in BankID (redirect) 
4. Go back to the app 
4. Crash

**Expected behavior**
Checkout goes fine 

**Device and version (please complete the following information):**
 - Device: all iPhones 
 - OS: 12, 13 (mostly 13.7) 
 - SDK Version: 1.6.6 

**Additional context**

Could be related to old SDK version (deprecated WebKit?)

**Comment by omarbh** [comment]
Hi @paweldziennik, could you provide some additional details:  
- which platform version the issue is occurring?
- is the issue happening on the demo app? 
Cheers

**Comment by ghost** [comment]
> Hi @paweldziennik, could you provide some additional details:
> 
> * which platform version the issue is occurring? 
> * is the issue happening on the demo app?
>   Cheers

Happening on iOS App
I was not able to reproduce to it on demo/test app. Also crash don't occur for 100% users on production app

**Comment by ghost** [comment]
Any update? Got quite a lot crashes recently for this issue. Maybe this stack trace will help you help me?

> Fatal Exception: NSInternalInconsistencyException
> 0  CoreFoundation                 0x1a7d81654 __exceptionPreprocess
> 1  libobjc.A.dylib                0x1a7aa3bcc objc_exception_throw
> 2  CoreFoundation                 0x1a7c846ec +[_CFXNotificationTokenRegistration keyCallbacks]
> 3  Foundation                     0x1a8118584 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:]
> 4  UIKitCore                      0x1ac2aa714 UIViewReportBrokenSuperviewChain
> 5  UIKitCore                      0x1ac2aaa84 _UIViewTopDownSubtreeTraversal
> 6  UIKitCore                      0x1ab807b88 -[UIViewController _setPresentationController:]
> 7  UIKitCore                      0x1ab80095c -[UIViewController _presentViewController:modalSourceViewController:presentationController:animationController:interactionController:completion:]
> 8  UIKitCore                      0x1ab802358 -[UIViewController _presentViewController:withAnimationController:completion:]
> 9  UIKitCore                      0x1ab804864 __63-[UIViewController _presentViewController:animated:completion:]_block_invoke
> 10 UIKitCore                      0x1ab804d6c -[UIViewController _performCoordinatedPresentOrDismiss:animated:]
> 11 UIKitCore                      0x1ab8047b4 -[UIViewController _presentViewController:animated:completion:]
> 12 UIKitCore                      0x1ab804a20 -[UIViewController presentViewController:animated:completion:]
> 13 Lets deal                      0x102988838 -[KCOCheckoutController showOverlayWithMessage:]
> 14 Lets deal                      0x10299d2a8 -[KCOWebViewProxy showFullscreenWithMessage:]
> 15 Lets deal                      0x10299395c __45-[KCOMessageProxy fullscreenShowHideHandlers]_block_invoke.43
> 16 Lets deal                      0x102984b34 __39-[KCOBaseMessageHandler handleMessage:]_block_invoke
> 17 libdispatch.dylib              0x1a7a469a8 _dispatch_call_block_and_release
> 18 libdispatch.dylib              0x1a7a47524 _dispatch_client_callout
> 19 libdispatch.dylib              0x1a7a2a6fc _dispatch_main_queue_callback_4CF$VARIANT$armv81
> 20 CoreFoundation                 0x1a7cff6bc __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
> 21 CoreFoundation                 0x1a7cfa590 __CFRunLoopRun
> 22 CoreFoundation                 0x1a7cf9ba8 CFRunLoopRunSpecific
> 23 GraphicsServices               0x1b1e70344 GSEventRunModal
> 24 UIKitCore                      0x1abe353e4 UIApplicationMain
> 25 Lets deal                      0x1025bb3f0 main + 25 (AppDelegate.swift:25)
> 26 libdyld.dylib                  0x1a7b818f0 start

**Comment by polar133** [comment]
Hi @paweldziennik we will look at it, thanks for the stacktrace that will help us a lot. Did you manage to reproduce it on dev/test environment?  there are newer versions where several bugs has been fixed, can you take a look at those and check if you can still reproduce the same behaviour?

**Comment by ghost** [comment]
Its no reproducible on dev env as it has no bankID option. But seems like new version fixes it (at least for some customers), will let you know if that issue can be closed after weekend. Thanks for help!

**Comment by polar133** [comment]
Hi @paweldziennik. let us know how did it went when you have better information please. thanks.

**Comment by ghost** [comment]
@polar133 Ok, seems like issue can be closed, thanks for help.
