### ISSUE TITLE
NSInvalidArgumentException: attempt to insert nil object from objects[0]

### ISSUE THREAD

**Issue by idrougge** [klarna/kco-mobile-sdk#57]
**Describe the bug**
Presenting `KCOKlarnaCheckout.checkoutViewController` results in exceptions as below:
```*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'```

**To Reproduce**
Call  `KCOKlarnaCheckout.checkoutViewController` before calling `KCOKlarnaCheckout.setSnippet`.

**Expected behavior**
If a snippet is necessary for creating the `checkoutViewController`, this should be enforced at init, or at least caught and reported at runtime. I found the cause of this issue only by luck.

**Device and version (please complete the following information):**
 - SDK Version: 1.6.14

**Comment by polar133** [comment]
Hi @idrougge, thanks for reaching out with this issue. 

I just try to reproduce it and couldn't found the same behaviour. Could you please share a snippet on how you are creating the KCOKlarnaCheckout and calling the checkoutViewController  ? 

the code that was tested : 
    
```
KCOKlarnaCheckout *checkout = [[KCOKlarnaCheckout alloc] initWithViewController:self returnURL:[NSURL URLWithString:@"fashionstore://"]];
UIViewController *viewController = checkout.checkoutViewController;
assert(viewController != nil);
```

**Comment by omarbh** [comment]
I will close this, @idrougge  please feel free to open it again if you still have the issue
