### ISSUE TITLE
Documentation refers to wrong pod

### ISSUE THREAD

**Issue by erik-kallen** [klarna/kco-mobile-sdk#68]
**Describe the bug**
The documentation at https://docs.klarna.com/in-app/checkout-sdk/checkout-ios-overview/ios-getting-started/ says to use `pod KlarnaCheckout`. It seems to me that it should be `pod KlarnaCheckoutSDK` instead.

**Comment by polar133** [comment]
Hi @erik-kallen, thanks for reporting the bug. We have already updated it. 👍
