### ISSUE TITLE
Expose the sizing events to Android

### ISSUE THREAD

**Issue by erik-kallen** [klarna/kco-mobile-sdk#70]
**Is your feature request related to a problem? Please describe.**
There appears to be no way to know how high the checkout should appear on Android

**Describe the solution you'd like**
The iOS SDK has a `sizingDelegate` whose `didResize` member will be invoked with the size that the checkout should appear to have.

I want to be able to use this in Android as well.

**Describe alternatives you've considered**
Perhaps it could be possible to sneak into the WebView, but that is hacky and seems brittle so I don't want to do it

**Comment by NMGuner** [comment]
Hi @erik-kallen, we haven't exposed such delegate/callback as Android allows you to use `wrap_content`, which has been working so far for our views. Do you have a use-case where that layout param is not working?

**Comment by erik-kallen** [comment]
Thanks for your reply.

My use case is that I want to embed the SDK inside of React-Native, and it appears that the size must be communicated back to React Native in order for its layout algorithm to work.

I have almost managed to solve this by using `mKlarnaCheckout.getView().addOnLayoutChangeListener()`. This is quite close to working, but:

* Immediately after I call `setSnippet`, my listener is invoked with a height of 2100 px.
* Then the checkout loads. After this happens, the required size for the checkout is increased slightly, but my onLayoutChangeListener does not get called (bad).
* After I do a suspend()/resume(), my onLayoutChangeListener is called (good).

So it does not work reliably.

I am new to Android, though, so I might be missing some other way of doing this.

**Comment by erik-kallen** [comment]
Turns out this isn't necessary, with enough hacking it was possible to make it work without it.

If someone ends up here from Google, what I did was

```
Choreographer.getInstance().postFrameCallback(new Choreographer.FrameCallback() {
    @Override
    public void doFrame(long frameTimeNanos) {
        View klarnaView = mKlarnaCheckout.getView();
        int width = klarnaView.getWidth();
        int height = klarnaView.getHeight();

        if (width != getWidth() || height != getHeight()) {
            measure(View.MeasureSpec.makeMeasureSpec(width, View.MeasureSpec.EXACTLY), View.MeasureSpec.makeMeasureSpec(height, View.MeasureSpec.EXACTLY));

            int left = getLeft();
            int top = getTop();
            layout(left, top, left + width, top + height);

            onSizeChange((int)PixelUtil.toDIPFromPixel(width), (int)PixelUtil.toDIPFromPixel(height));

            getViewTreeObserver().dispatchOnGlobalLayout();
        }

        Choreographer.getInstance().postFrameCallback(this);
    }
});
```
