### ISSUE TITLE
Version 1.7.x seems to not be available for Android.

### ISSUE THREAD

**Issue by erik-kallen** [klarna/kco-mobile-sdk#71]
**Describe the bug**
According to the releases/ branches, there seems to be a release 1.7.0 for Android. However, Gradle fails to resolve this dependency. It can resolve 1.6.15 without issue, but not 1.7.x

build.gradle:

```
allprojects {
    repositories {
        ... other stuff ...
        maven {
            url 'https://x.klarnacdn.net/mobile-sdk/'
        }
    }
}
```

And 

```
dependencies {
    ... other stuff ...
    implementation 'com.klarna.checkout:sdk:1.7.0'
}
```

**Comment by NMGuner** [comment]
Hi @erik-kallen, can you please check if you can access [maven metadata](https://x.klarnacdn.net/mobile-sdk/com/klarna/checkout/sdk/maven-metadata.xml) and [AAR file](https://x.klarnacdn.net/mobile-sdk/com/klarna/checkout/sdk/1.7.1/sdk-1.7.1.aar). What we suspect is, it may be a VPN/internal network issue if the version 1.6.15 of the SDK is already cached in your local gradle.

**Comment by erik-kallen** [comment]
Thank you for your reply.

For some reason it worked today. Exactly the same office network as I was on yesterday, so I don't understand it at all.
