### ISSUE TITLE
SDK does not redirect to bank authorization

### ISSUE THREAD

**Issue by eljass** [klarna/kco-mobile-sdk#73]
**Describe the bug**
The payment gets stuck on opening the Klarna window. If the user cancels the payment he/she cannot get back to the main application, or if they select a bank, the bank's page does not open from the window. 

This works correctly with demo credentials on KCO. It opens Chrome (on Android) and Safari (on iOS) and there is the possibility to "authorize" or "deny" the payment. Window redirects back to the app. So, it seems that there are some issues with production credentials and behavior Klarna do after that.

We are using Capacitor.js and the plugin we created for KCO to integrate in-app SDKs for it. The source for that plugin can be found here for further investigation if something should work differently from your point of view: https://github.com/Fiksuruoka-fi/capacitor-klarna-kco

**To Reproduce**
Steps to reproduce the redirect behavior:
1. Select Klarna bank payment
2. Click on 'Pay'
3. Click bank name
4. Click "proceed" to authorize
5. Window does not redirect to bank's webpage

Steps to reproduce the cancel behavior:
1. Select Klarna bank payment
2. Click on 'Pay'
3. Cancel payment in the opened window
4. Screen does not hide and the user cannot get back to the app

**Expected behavior**
Klarna window should redirect to the bank's authorization page in the user's browser, or back to the main application if payment is canceled.

**Screenshots**
Cancel payment fail:
https://user-images.githubusercontent.com/7661970/166152691-6bdf589e-0c71-4cc9-900b-6a813b3db9c9.mov

Redirect to bank authorization fail:
https://user-images.githubusercontent.com/7661970/166152768-d6f2b01f-4ca9-4d58-8248-52903cd7961f.mov

**Device and version (please complete the following information):**
 - Device: iPhone 13, Android
 - OS: iOS 15.4, Android 10
 - SDK Version: iOS 1.7.2, Android 1.7.1
 
**Merchant Name**
Fiksu Ruoka Oy, Fiksuruoka.fi

**Impact Level**
**High**, this blocks us from using in-app SDK for checkout. Therefore, this limits suitable UX for our customers to pay in our app. Also, this blocks further development as we cannot release this before the checkout flow works as expected.

**Comment by polar133** [comment]
Hi @eljass, thanks for reaching out. 

Sorry for the late reply. We were informed that this issue is fixed. There aren't changes in the codebase. Please, try again and let us know how it did goes.

**Comment by eljass** [comment]
Hi @polar133,

Yes, this was fixed and now the SDK opens a new WebView for Sofort. There are still some UX issues on that and the full-screen modal. I reported those by email to our Klarna contact, but to inform you guys as well:

1. When Sofort WebView opens there are now two "x" buttons in the upper right corner. One inside the website content (includes asking the reason for cancellation) and one on top of the WebView which closes the WebView.
2. If the customer cancels the payment from either of those they are still shown the full-screen modal which prompts them to continue to pay with a bank account.
  a) Now if the customer clicks x on this screen he/she is able to continue switching the payment method and clicking the "Pay" button again
  b) If the customer clicks the "Proceed" button the full-screen modal closes but the "Pay" button at the bottom of the KCO widget is inactive and does not accept click events. Therefore the customer is stuck on paying.

The main issue here is that the "Proceed" button is much more attractive than the small "x" button in the top right corner, and they most likely get stuck in payment.
 
Scenario 1: Clicking "Proceed" on the full-screen modal after canceling:
https://user-images.githubusercontent.com/7661970/169574977-edb13afa-e6f1-4f75-a517-87cb0ec8a979.mp4

Scenario 2: Clicking "x" on the full-screen modal after canceling:
https://user-images.githubusercontent.com/7661970/169575344-dbaab0f7-ee8c-4ea1-b5c3-71a935e14326.mp4

We still have to test the successful payment, which is a little hard as it has to be made on the production account since when using playground MID it redirects to Klarna's own webpage in the native browser (or at least this was the case earlier when we reported the bug).

**Comment by eljass** [comment]
Any updates on this @polar133?

**Comment by NMGuner** [comment]
Closing due to stale state of the issue and due to this library being deprecated, please consider integrating [Klarna Mobile SDK](https://github.com/klarna/klarna-mobile-sdk).
