### ISSUE TITLE
Payment stuck at "Connecting to bank" after 3rd party completion (bankid)

### ISSUE THREAD

**Issue by russnes** [klarna/kco-mobile-sdk#75]
**Describe the bug**
After paying with Klarna labeled credit card, the Klarna view is stuck at "Connecting to your bank". Upon clicking on the top-right X, it proceeds successfully. This is happening both on Android and on iOS.

I noticed the following in the logs on our Android device:

        "SDK Lib error: Parsing JSON. SyntaxError: Unexpected token < in JSON at position 0", source: https://cards-eu.klarna.com/gui/modern-13.4.0/bundle-card-123.js (63)

See pastebin for more logs and deobfuscated javascript link:
https://pastebin.com/raw/QZ8zfCf4

**To Reproduce**
1. Make a payment with a Credit card, using the option with Klarna label.
2. Enter information, get directed to verify with BankID
3. Complete verification, return to app.

**Screenshots**
![screen_koblertil](https://user-images.githubusercontent.com/1278451/189050775-cc04c45e-f1c2-4173-afe8-3df8dc6793c9.png)

**Device and version (please complete the following information):**
 - Device: iPhone SE 15.6.1 and Android Emulator API 30
 - SDK Version 1.7.3 (1.7.2 for android)

**Impact Level**
Blocking production app

**Additional context**
I was able to get it to work previously, but upon testing later it had stopped working. Not sure if this is the actual problem but parsing the external JavaScript library would fit the problem as nothing changed locally in the app.

**Comment by NMGuner** [comment]
Hi @russnes, thanks for reporting the issue. We will be doing the investigation with Klarna Checkout team and others. 

In order to speed up the process, would you be able to provide any Klarna session or order IDs with us please.

**Comment by russnes** [comment]
Hi @NMGuner 
Sure, here is an order id that I just created on my end:
e4a8c479-b243-4982-a371-8a8d5175b0ee

**Comment by russnes** [comment]
Hi again. I haven't had time to test extensively yet, but as our implementation is a React native app with wrapped native components, we found an issue where our app would reload the Klarna view as the app entered the background, so it might have been the issue that the Klarna view got re-created during the payment.

I will debug more later but I will close the issue for now and re-open if we still experience the after more testing.
