### ISSUE TITLE
Redirection to external payment stuck on loading screen

### ISSUE THREAD

**Issue by eljass** [klarna/kco-mobile-sdk#76]
**Describe the bug**
The loading screen does not close once redirected to the external payment method page.

**To Reproduce**
1. Load KCO widget
2. Select an external payment method and click "Select xxx"
3. Navigate inside SPA to another page where there is no Klarna widget present
4. Opened "Redirecting to the payment page" modal does not close

**Expected behavior**
Once redirection is done on the site, the loading screen should hide so content underneath would be accessible.

**Screenshots**
![Simulator Screen Shot - iPhone 14 - 2022-10-26 at 22 50 50](https://user-images.githubusercontent.com/7661970/198123754-f8f909ad-43bf-4b78-af23-35da3e278345.png)

![Simulator Screen Shot - iPhone 14 - 2022-10-26 at 22 50 56](https://user-images.githubusercontent.com/7661970/198123745-e6e4a72a-d53d-42cf-a6df-d42cda9f55da.png)

![Simulator Screen Shot - iPhone 14 - 2022-10-26 at 22 54 20](https://user-images.githubusercontent.com/7661970/198123728-7c491764-c620-42a2-934b-73964f49faa1.png)

**Device and version (please complete the following information):**
 - Device: iPhone14 (simulator)
 - OS: iOS16.0
 - SDK Version 1.7.3
 
**Merchant Name**
Fiksuruoka.fi / Foodello

**Impact Level**
This is blocking our app release in new markets where we use external payment methods.

**Comment by gbanfalvikl** [comment]
Hi! Are you setting the "Handles external payment methods" flag before setting the snippet?

**Comment by eljass** [comment]
@gbanfalvikl 
Hi, 
Yes, I do think so. We use Capacitor plugin for this and you can see how it's initialized from here if you could pinpoint any issues:
https://github.com/Fiksuruoka-fi/capacitor-klarna-kco/blob/14c092dd55f0489bbad96bbe637f84ec1ee45d65/ios/Plugin/KlarnaKco.swift#L95-L115

**Comment by NMGuner** [comment]
Closing due to stale state of the issue and due to this library being deprecated, please consider integrating [Klarna Mobile SDK](https://github.com/klarna/klarna-mobile-sdk).
