### ISSUE TITLE
KlarnaCheckout.h not found when building release for emulator

### ISSUE THREAD

**Issue by erik-kallen** [klarna/kco-mobile-sdk#77]
**Describe the bug**

I have an ios app that uses the KlarnaCheckoutSDK pod. One of my .h files then contains

```
#import <KlarnaCheckoutSDK/KlarnaCheckout.h>
```

This works, except that when I try to build a release build for the emulator target, I get an error saying that KlarnaCheckout.h does not exist. This happens for all team members, and always for this file (even though we use 10s of other pods)

**Expected behavior**
It should be possible to build release versions for the emulator

**Comment by NMGuner** [comment]
Closing due to stale state of the issue and due to this library being deprecated, please consider integrating [Klarna Mobile SDK](https://github.com/klarna/klarna-mobile-sdk).
