### ISSUE TITLE
KCOCheckoutViewControllerProtocol type of checkoutViewController not visible to swift

### ISSUE THREAD

**Issue by hannseman** [klarna/kco-mobile-sdk#9]
When accessing the `checkoutViewController` swift has no idea of the requirement of conformance of `KCOCheckoutViewControllerProtocol`

From the `KCOKlarnaCheckout.h`:

``` swift
@property(nonatomic, readonly) UIViewController<KCOCheckoutViewControllerProtocol> *checkoutViewController;
```

From swift:

``` swift
public var checkoutViewController: UIViewController! { get }
```

This makes it awkward to set properties like `sizingDelegate`, `parentScrollView` and `internalScrollDisabled`. Resulting in `Value of type 'UIViewController' has no member 'sizingDelegate'`.

**Comment by omarbh** [comment]
Hi @hannseman we have release a fix! could you check this. I will close this issue.
